#include "clean_stock_sram.hpp"

#include <cstdlib>
#include <cstring>
#include <string_view>

namespace ur::product {
namespace {

// Canonical source:
// reference/imported/reverse-engineering/dessyreqt/SRAM/Clean.srm
// Git blob: f5c722385bca6c08fd27e47999684b05036bea4b
// Base64 keeps the exact 8 KiB stock image self-contained in the shipping
// binary without depending on the repository fixture at runtime.
constexpr std::string_view kCleanStockSramBase64 =
    "QVNKSXZlcjMuMzD/bWlrZV9fX1///19fX19fX2FuZHJld19f//9fX19fX19tYXJ0aW5fX///X19fX19fbWVsaXNzYV///19f"
    "X19fX2FteV9fX19f//9fX19fX19tYWxjb2xtX///X19fX19fbWljaGVsbGX//19fX19fX2NvbGluX19f//9fX19fX19kYXZl"
    "X19fX///X19fX19fdG9ueV9fX1///19fX19fX2Nhcm9sX19f//9fX19fX19jcmFpZ19fX///X19fX19fa2VuX19fX1///19f"
    "X19fX3JvYmJpZV9f//9fX19fX19hbGljZV9fX///X19fX19fc3RldmVfX1///19fX19fX3NvbWVvbmVf//9fX19fX19icm9u"
    "c2VuX///X19fX19fc2lsdmlhX1///19fX19fX2dvbGR3eW5f//9fX19fX19hbnRpLXVuaf//X19fX19fAABkZWZpbmVfbWX/"
    "/19fX5ewZGVmaW5lX21l//9fX19fX19fX19fX19fX19fX19fX/9kZWZpbmVfbWX//19fX19fX19fX19fX19fX19fX19f/2Rl"
    "ZmluZV9tZf//X19fX19fX19fX19fX19fX19fX1//ZGVmaW5lX21l//9fX19fX19fX19fX19fX19fX19fX/9kZWZpbmVfbWX/"
    "/19fX19fX19fX19fX19fX19fX19f/2RlZmluZV9tZf//X19fX19fX19fX19fX19fX19fX1//JiAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABg6mDqAABg6mDqYOpg6gAAYOpg6mDq"
    "YOoAAGDqYOpg6mDqAABg6mDqYOpg6gAAYOpg6mDqYOoAAGDqYOpg6mDqAABg6mDqYOpg6gAAYOpg6mDqYOoAAGDqYOpg6mDq"
    "AABg6mDqYOpg6gAAYOpg6mDqYOoAAGDqYOpg6mDqAABg6mDqYOpg6gAAYOpg6mDqYOoAAGDqYOpg6mDqAABg6mDqYOpg6gAA"
    "YOpg6mDqYOoAAGDqYOpg6mDqAABg6mDqYOpg6gAAYOpg6mDqYOoAAGDqYOpg6mDqAABg6mDqYOpg6gAAYOpg6mDqYOoAAGDq"
    "YOpg6mDqAABg6mDqYOpg6gAAYOpg6mDqYOoAAGDqYOpg6mDqAABg6mDqYOpg6gAAYOpg6mDqYOoAAGDqYOoA3RAQEBAQEBAQ"
    "EBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ"
    "EBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQELC0"
    "EBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAACAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAPCRAAAAAAAABAAAAEhlcmVUb2//"
    "i8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AF/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf"
    "6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf"
    "6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oA"
    "AF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf"
    "6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf"
    "6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf"
    "6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf"
    "6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oA"
    "AF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf"
    "6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf"
    "6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf"
    "6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf"
    "6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oA"
    "AF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf"
    "6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf"
    "6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf"
    "6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf"
    "6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oA"
    "AF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf"
    "6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf"
    "6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf"
    "6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf6gAAX+pf6l/qX+oAAF/qX+pf6l/qAABf6l/qX+pf"
    "6gAAX+pf6l/qX+oAAF/qX+qA7QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIZXJlVG9v/wAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
;

int decode_base64_char(char ch) noexcept {
    if (ch >= 'A' && ch <= 'Z') return ch - 'A';
    if (ch >= 'a' && ch <= 'z') return 26 + ch - 'a';
    if (ch >= '0' && ch <= '9') return 52 + ch - '0';
    if (ch == '+') return 62;
    if (ch == '/') return 63;
    return -1;
}

std::array<std::uint8_t, kStockSramBytes> decode_clean_stock_sram() noexcept {
    std::array<std::uint8_t, kStockSramBytes> out{};
    std::size_t out_index = 0;
    std::uint32_t accumulator = 0;
    unsigned bits = 0;

    for (const char ch : kCleanStockSramBase64) {
        if (ch == '=') break;
        const int value = decode_base64_char(ch);
        if (value < 0) std::abort();
        accumulator = (accumulator << 6u) |
            static_cast<std::uint32_t>(value);
        bits += 6u;
        if (bits >= 8u) {
            bits -= 8u;
            if (out_index >= out.size()) std::abort();
            out[out_index++] = static_cast<std::uint8_t>(
                (accumulator >> bits) & 0xffu);
            if (bits == 0u) {
                accumulator = 0;
            } else {
                accumulator &= (1u << bits) - 1u;
            }
        }
    }

    if (out_index != out.size()) std::abort();
    return out;
}

}  // namespace

const std::array<std::uint8_t, kStockSramBytes>& clean_stock_sram() noexcept {
    static const auto image = decode_clean_stock_sram();
    return image;
}

bool stock_sram_format_signature_present(
    const std::uint8_t* data, std::size_t size) noexcept {
    if (!data || size != kStockSramBytes) return false;
    return std::memcmp(
               data,
               clean_stock_sram().data(),
               kStockSramFormatSignatureBytes) == 0;
}

}  // namespace ur::product
