#!/usr/bin/env python3
"""Decode every RNC Method 1 stream in every preserved ROM and emit a compact manifest."""
from pathlib import Path
import hashlib
import json
import math
from collections import Counter
from rnc_method1 import parse_header, unpack_method1, RNCError

ROMS = {
    "usa-retail": Path("reference/roms/retail/Uniracers_USA.sfc"),
    "europe-retail": Path("reference/roms/retail/Unirally_Europe.sfc"),
    "legacy-beta": Path("reference/roms/prototypes/Uniracers_Beta_legacy.sfc"),
    "pal-prototype-1994-11-29": Path("reference/roms/prototypes/Unirally_1994-11-29_PAL_prototype.sfc"),
}
JSON_OUT=Path("analysis/generated/rnc-stream-manifest.json")
MD_OUT=Path("analysis/generated/rnc-stream-manifest.md")

def find_streams(data: bytes):
    pos=0
    while True:
        off=data.find(b"RNC\x01",pos)
        if off < 0: return
        try:
            h=parse_header(data[off:off+18])
        except RNCError:
            pos=off+1; continue
        end=off+18+h.packed_size
        if h.packed_size and h.unpacked_size and end <= len(data):
            yield off,data[off:end],h
        pos=off+1

def entropy(data: bytes) -> float:
    if not data: return 0.0
    counts=Counter(data); n=len(data)
    return -sum((v/n)*math.log2(v/n) for v in counts.values())

def periodic_equal_fraction(data: bytes, shift: int) -> float:
    if len(data) <= shift: return 0.0
    n=len(data)-shift
    return sum(a==b for a,b in zip(data[:-shift],data[shift:]))/n

def main():
    manifest={"schema_version":1,"roms":{}}
    failures=[]
    for name,path in ROMS.items():
        data=path.read_bytes()
        entries=[]
        for idx,(off,packed,h) in enumerate(find_streams(data),1):
            try:
                decoded=unpack_method1(packed)
            except Exception as e:
                failures.append((name,idx,off,str(e)))
                continue
            entries.append({
                "index":idx,
                "offset":off,
                "packed_size":h.packed_size,
                "unpacked_size":h.unpacked_size,
                "packed_crc16":f"{h.packed_crc:04x}",
                "unpacked_crc16":f"{h.unpacked_crc:04x}",
                "packed_sha256":hashlib.sha256(packed).hexdigest(),
                "unpacked_sha256":hashlib.sha256(decoded).hexdigest(),
                "zero_fraction":round(decoded.count(0)/len(decoded),6),
                "distinct_bytes":len(set(decoded)),
                "entropy_bits_per_byte":round(entropy(decoded),6),
                "equal_fraction_shift_256":round(periodic_equal_fraction(decoded,256),6),
                "divisible_by_256":len(decoded)%256==0,
                "divisible_by_4096":len(decoded)%4096==0,
            })
        manifest["roms"][name]={"path":str(path),"count":len(entries),"streams":entries}

    if failures:
        detail="; ".join(f"{a} #{i} @0x{o:X}: {e}" for a,i,o,e in failures[:10])
        raise SystemExit(f"RNC decode failures ({len(failures)}): {detail}")
    counts={name:r["count"] for name,r in manifest["roms"].items()}
    if any(v != 45 for v in counts.values()):
        raise SystemExit(f"expected 45 decoded streams per ROM, got {counts}")

    JSON_OUT.parent.mkdir(parents=True,exist_ok=True)
    JSON_OUT.write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8")

    lines=[
        "# Verified RNC Method 1 Stream Manifest","",
        "Generated by `tools/analyze_rnc_streams.py` using the project-owned Python decoder in `tools/rnc_method1.py`. Every listed stream passed both its packed CRC16 and unpacked CRC16 checks.","",
        "## Corpus summary","",
        "| Build | Decoded streams | Unique decoded outputs |",
        "|---|---:|---:|",
    ]
    for name,r in manifest["roms"].items():
        uniq=len({x["unpacked_sha256"] for x in r["streams"]})
        lines.append(f"| {name} | {r['count']} | {uniq} |")

    usa=manifest["roms"]["usa-retail"]["streams"]
    pal=manifest["roms"]["europe-retail"]["streams"]
    lines += ["","## USA vs PAL retail decoded deltas","",
              "| # | USA unpacked | PAL unpacked | Same decoded bytes | USA decoded SHA-256 | PAL decoded SHA-256 |",
              "|---:|---:|---:|:---:|---|---|"]
    for u,p in zip(usa,pal):
        same=u["unpacked_sha256"]==p["unpacked_sha256"]
        if not same:
            lines.append(f"| {u['index']} | {u['unpacked_size']:,} | {p['unpacked_size']:,} | no | `{u['unpacked_sha256']}` | `{p['unpacked_sha256']}` |")

    lines += ["","## USA retail decoded stream characteristics","",
              "| # | Offset | Packed | Unpacked | Zero % | Distinct bytes | Entropy | eq(i,i+256) | /256 | /4096 | Decoded SHA-256 |",
              "|---:|---:|---:|---:|---:|---:|---:|---:|:---:|:---:|---|"]
    for x in usa:
        lines.append(f"| {x['index']} | `0x{x['offset']:06X}` | {x['packed_size']:,} | {x['unpacked_size']:,} | {100*x['zero_fraction']:.2f} | {x['distinct_bytes']} | {x['entropy_bits_per_byte']:.3f} | {x['equal_fraction_shift_256']:.3f} | {'yes' if x['divisible_by_256'] else 'no'} | {'yes' if x['divisible_by_4096'] else 'no'} | `{x['unpacked_sha256']}` |")
    lines += ["","Raw decoded payloads are intentionally not committed; regenerate locally from the preserved reference ROMs.",""]
    MD_OUT.write_text("\n".join(lines),encoding="utf-8")
    print(f"decoded 45 streams in each of {len(ROMS)} ROMs")
    print(JSON_OUT); print(MD_OUT)

if __name__=="__main__":
    main()
