#!/usr/bin/env python3
# Static archaeological baseline; safe to rerun whenever reference ROMs change.
from pathlib import Path
import hashlib

RETAIL=Path("reference/roms/retail/Uniracers_USA.sfc")
PROTO=Path("reference/roms/prototypes/Unirally_1994-11-29_PAL_prototype.sfc")
OUT=Path("analysis/generated/retail-vs-prototype-structure.md")

def be32(b): return int.from_bytes(b,"big")
def be16(b): return int.from_bytes(b,"big")

def header(data):
    h=data[0x7FC0:0x8000]
    title=h[:21].rstrip(b"\x00 ").decode("ascii","replace")
    return title,h[0x15],h[0x16],h[0x17],h[0x18],h[0x19],h[0x1A],h[0x1B],int.from_bytes(h[0x1C:0x1E],"little"),int.from_bytes(h[0x1E:0x20],"little")

def rnc(data):
    out=[]; pos=0
    while True:
        i=data.find(b"RNC",pos)
        if i<0: break
        e={"off":i,"method":data[i+3] if i+3<len(data) else -1,"valid":False}
        if i+18<=len(data) and e["method"] in (1,2):
            u=be32(data[i+4:i+8]); p=be32(data[i+8:i+12])
            e.update(unpacked=u,packed=p,ucrc=be16(data[i+12:i+14]),pcrc=be16(data[i+14:i+16]),leeway=data[i+16],chunks=data[i+17],valid=(u>0 and p>0 and i+18+p<=len(data)))
        out.append(e); pos=i+1
    return out

def diff_runs(a,b):
    n=min(len(a),len(b)); runs=[]; diff=0; i=0
    while i<n:
        if a[i]==b[i]: i+=1; continue
        s=i
        while i<n and a[i]!=b[i]: i+=1
        runs.append((s,i)); diff+=i-s
    if len(a)!=len(b):
        runs.append((n,max(len(a),len(b)))); diff+=abs(len(a)-len(b))
    return runs,diff

def main():
    a=RETAIL.read_bytes(); b=PROTO.read_bytes()
    ar=rnc(a); br=rnc(b); runs,diff=diff_runs(a,b)
    lines=["# Retail vs. PAL Prototype Structural Report","",
           "Generated by tools/analyze_reference_roms.py. Observations below are not semantic conclusions.","",
           "## Identity",""]
    for name,path,data in [("USA retail",RETAIL,a),("1994-11-29 PAL prototype",PROTO,b)]:
        h=header(data)
        lines += [f"- **{name}:** {path}",f"  - size: {len(data):,} bytes",f"  - SHA-256: {hashlib.sha256(data).hexdigest()}",
                  f"  - LoROM header candidate at 0x7FC0: title={h[0]!r}; map=0x{h[1]:02X}; cart=0x{h[2]:02X}; rom=0x{h[3]:02X}; sram=0x{h[4]:02X}; region=0x{h[5]:02X}; developer=0x{h[6]:02X}; version=0x{h[7]:02X}; complement=0x{h[8]:04X}; checksum=0x{h[9]:04X}"]
    lines += ["","## RNC header scan",""]
    for name,hits in [("USA retail",ar),("PAL prototype",br)]:
        valid=[x for x in hits if x["valid"]]
        lines += [f"### {name}","",f"Found {len(hits)} ASCII RNC occurrences; {len(valid)} parse as plausible Method 1/2 headers.",""]
        if valid:
            lines += ["| Offset | Method | Packed | Unpacked | Packed CRC | Unpacked CRC | Leeway | Chunks |","| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
            for x in valid:
                lines.append(f"| 0x{x['off']:06X} | {x['method']} | {x['packed']:,} | {x['unpacked']:,} | 0x{x['pcrc']:04X} | 0x{x['ucrc']:04X} | {x['leeway']} | {x['chunks']} |")
            lines.append("")
    lines += ["## Raw binary difference","",f"- differing bytes: {diff:,} / {max(len(a),len(b)):,}",f"- contiguous differing runs: {len(runs):,}","- 25 largest differing runs:"]
    for ln,s,e in sorted(((e-s,s,e) for s,e in runs),reverse=True)[:25]:
        lines.append(f"  - 0x{s:06X}-0x{e-1:06X}: {ln:,} bytes")
    ak={(x.get("method"),x.get("packed"),x.get("unpacked"),x.get("pcrc"),x.get("ucrc")):x for x in ar if x["valid"]}
    bk={(x.get("method"),x.get("packed"),x.get("unpacked"),x.get("pcrc"),x.get("ucrc")):x for x in br if x["valid"]}
    common=set(ak)&set(bk)
    lines += ["","## RNC cross-build comparison","",f"- matching RNC header/content tuples across builds: {len(common)}"]
    for k in sorted(common,key=lambda k:ak[k]["off"])[:100]:
        lines.append(f"  - retail 0x{ak[k]['off']:06X} <-> prototype 0x{bk[k]['off']:06X}; method {k[0]}, packed {k[1]:,}, unpacked {k[2]:,}")
    lines += ["","## Next discriminating steps","",
              "1. Independently decompress every plausible stream.",
              "2. Locate the game decompressor and compare its structure with preserved RNC_1.S and RNC_2.S.",
              "3. Classify large retail/prototype diff runs as code, graphics, audio, compressed data, tables, or region changes.",
              "4. Cross-reference outputs with the historical 256-tile-width claim and 7E:2080 course-load breadcrumb.",
              "5. Use known TAS WRAM anchors and Canoe patch hooks as additional disassembly landmarks.",""]
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text("\n".join(lines),encoding="utf-8")
    print(OUT)

if __name__=="__main__": main()
