#!/usr/bin/env python3
"""Generate a compact audit of imported Uniracers-specific source assumptions."""

from __future__ import annotations

from collections import Counter
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "analysis" / "generated" / "third-party-code-audit.md"

TARGETS = {
    "Snes9x 1.43 DMA": ROOT / "references/imported/emulators/snes9x-1.43/dma.cpp",
    "Snes9x pinned DMA": ROOT / "references/imported/emulators/snes9x/dma.cpp",
    "Snes9x pinned ROM hacks": ROOT / "references/imported/emulators/snes9x/memmap.cpp",
    "jgenesis sprites": ROOT / "references/imported/emulators/jgenesis/sprites.rs",
    "MAME SNES PPU": ROOT / "references/imported/emulators/mame/snes_ppu.cpp",
    "2014 Tabletop bot": ROOT / "references/imported/tas-bots/uniracers-tabletop-bot-2014.lua",
}


def source_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8", errors="replace").splitlines()


def named_lines(lines: list[str], pattern: str) -> list[tuple[int, str]]:
    rx = re.compile(pattern, re.IGNORECASE)
    return [(i, line.strip()) for i, line in enumerate(lines, 1) if rx.search(line)]


def duplicate_lua_keys(lines: list[str]) -> list[tuple[str, int, int]]:
    tables: list[dict[str, int]] = []
    out: list[tuple[str, int, int]] = []
    key_rx = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=")
    for lineno, raw in enumerate(lines, 1):
        line = raw.split("--", 1)[0]
        for _ in range(line.count("{")):
            tables.append({})
        if tables:
            m = key_rx.match(line)
            if m:
                key = m.group(1)
                first = tables[-1].get(key)
                if first is None:
                    tables[-1][key] = lineno
                else:
                    out.append((key, first, lineno))
        for _ in range(line.count("}")):
            if tables:
                tables.pop()
    return out


def main() -> int:
    data = {name: source_lines(path) for name, path in TARGETS.items()}

    old = named_lines(data["Snes9x 1.43 DMA"], r"SNESGameFixes\.Uniracers")
    new_dma = named_lines(data["Snes9x pinned DMA"], r"SNESGameFixes\.Uniracers")
    new_map = named_lines(data["Snes9x pinned ROM hacks"], r"UNIRACERS|Uniracers")
    jgen = named_lines(data["jgenesis sprites"], r"Uniracers")
    mame = named_lines(data["MAME SNES PPU"], r"Uniracers|This is a hack")
    bot_lines = data["2014 Tabletop bot"]
    duplicates = duplicate_lua_keys(bot_lines)
    signed_bug = named_lines(bot_lines, r"word\s*>\s*32768")

    if not old:
        raise SystemExit("expected historical Snes9x Uniracers special case not found")
    if not new_dma or not new_map:
        raise SystemExit("expected pinned Snes9x Uniracers special handling not found")
    if len(jgen) != 1 or not jgen[0][1].lstrip().startswith("//"):
        raise SystemExit("jgenesis Uniracers reference is no longer comment-only; re-audit required")
    if not any("hack" in line.lower() for _, line in mame):
        raise SystemExit("expected MAME active-display hack caveat not found")
    if not duplicates:
        raise SystemExit("expected duplicate Lua table keys not found")
    if not signed_bug:
        raise SystemExit("expected recovered bot signed-boundary bug not found")

    duplicate_counts = Counter(key for key, _, _ in duplicates)
    lines = [
        "# Generated Third-Party Code Audit",
        "",
        "Generated by `tools/audit_imported_code.py`. This report records source structure, not hardware truth.",
        "",
        "## Emulator implementation posture",
        "",
        "| Imported source | Uniracers-specific structure | Audit interpretation |",
        "|---|---|---|",
        f"| Snes9x 1.43 DMA | named special-case at line(s) {', '.join(str(n) for n,_ in old)} | historical game-specific workaround |",
        f"| pinned Snes9x DMA + ROM hacks | named handling at DMA line(s) {', '.join(str(n) for n,_ in new_dma)}; ROM-hack line(s) {', '.join(str(n) for n,_ in new_map)} | still game-specific; not an independent generic hardware model |",
        f"| jgenesis sprites | Uniracers appears only in a comment at line {jgen[0][0]} | generic sprite/OAM state model; strongest architecture reference of these imports |",
        f"| MAME SNES PPU | relevant references/caveat at line(s) {', '.join(str(n) for n,_ in mame)} | independent implementation, but source explicitly describes the treatment as a hack |",
        "",
        "## Recovered 2014 bot source hazards",
        "",
        f"- Duplicate named Lua table keys detected: {len(duplicates)} occurrences across {len(duplicate_counts)} names.",
        f"- Duplicated names: {', '.join(sorted(duplicate_counts))}.",
        f"- `MakeWordSigned` uses the strict `> 32768` comparison at line(s) {', '.join(str(n) for n,_ in signed_bug)}, so raw `0x8000` is mishandled.",
        "- Preserve this source unchanged as evidence; normalize any promoted behavior in project-owned code.",
        "",
        "## Decision consequence",
        "",
        "Do not count the two Snes9x snapshots as independent hardware corroboration. For active-display OAM behavior, prioritize deterministic ROM evidence and generic state-machine models; use game-specific emulator hacks as regression history.",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
