#!/usr/bin/env python3
"""Fail-closed device-rate acceptance for real packaged Windows SDL3 output.

The PCM and production-queue metrics must already be generated by the trusted
SDL-disk and SNESRecomp reducers. This gate checks that a requested alternate
Windows output-device rate genuinely reached the device and both channels,
without interpreting guest cadence or claiming exact sample/music parity.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def check_rate(output: dict, queue: dict, *, requested_rate: int = 48000) -> dict:
    if requested_rate not in (44100, 48000):
        raise ValueError("unsupported explicit Windows audio rate probe")
    if (output.get("schema_version") != 1
        or output.get("audio_origin") != "sdl3-disk-playback"
        or output.get("device_format") not in ("S16LE", "S16")
        or output.get("channels") != 2
        or output.get("sample_rate") != requested_rate
        or output.get("tail_pcm_frames") != requested_rate
        or output.get("tail_duration_seconds") != 1.0):
        raise ValueError("SDL device did not negotiate requested stereo S16 one-second rate")
    channels = output.get("tail_channel_rms")
    if (not isinstance(channels, list) or len(channels) != 2
        or any(not isinstance(x, (int, float)) or isinstance(x, bool)
               or not math.isfinite(x) or x < 50 for x in channels)):
        raise ValueError("alternate-rate SDL device lacks audible stereo channel tails")
    duration = output.get("duration_seconds")
    if (not isinstance(duration, (int, float)) or isinstance(duration, bool)
        or not math.isfinite(duration) or not 10 <= duration <= 90):
        raise ValueError("alternate-rate SDL output duration is invalid")
    if (queue.get("schema_version") != 1
        or queue.get("audio_origin") != "snesrecomp-production-audio-stats"):
        raise ValueError("missing authentic Release source-queue statistics")
    deltas = queue.get("post_startup_deltas")
    if (not isinstance(deltas, dict)
        or any(deltas.get(key) != 0 for key in (
            "dropped_audible", "underflows", "missing_frames"))):
        raise ValueError("alternate-rate Windows playback had post-startup audio loss")
    if queue.get("snapshots", 0) < 3:
        raise ValueError("alternate-rate queue continuity lacks enough snapshots")
    return {
        "schema_version": 1,
        "device_origin": "sdl3-disk-playback",
        "device_rate_hz": requested_rate,
        "channels": 2,
        "last_one_second_channel_rms": channels,
        "captured_duration_seconds": duration,
        "release_audio_queue_post_startup_loss": 0,
        "limits": "stereo presence and steady continuity, not exact SPC/DSP equality or latency",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("device_output", type=Path)
    parser.add_argument("production_queue", type=Path)
    parser.add_argument("--expected-rate", type=int, default=48000)
    parser.add_argument("--json-out", type=Path, required=True)
    args = parser.parse_args()
    report = check_rate(
        json.loads(args.device_output.read_text(encoding="utf-8")),
        json.loads(args.production_queue.read_text(encoding="utf-8")),
        requested_rate=args.expected_rate,
    )
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(
        "WINDOWS_NATIVE_AUDIO_DEVICE_RATE PASS "
        f"rate={report['device_rate_hz']} channels=2 "
        f"left_rms={report['last_one_second_channel_rms'][0]:.2f} "
        f"right_rms={report['last_one_second_channel_rms'][1]:.2f} "
        "post_startup_loss=0"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
