#!/usr/bin/env python3
"""Pairwise structural comparison across all preserved Uniracers/Unirally ROM builds."""
from pathlib import Path
import hashlib
import itertools

ROMS = {
    "USA retail": Path("reference/roms/retail/Uniracers_USA.sfc"),
    "Europe retail": Path("reference/roms/retail/Unirally_Europe.sfc"),
    "Legacy GoodSNES beta": Path("reference/roms/prototypes/Uniracers_Beta_legacy.sfc"),
    "1994-11-29 PAL prototype": Path("reference/roms/prototypes/Unirally_1994-11-29_PAL_prototype.sfc"),
}
OUT = Path("analysis/generated/reference-rom-comparison.md")

def be32(b): return int.from_bytes(b, "big")
def be16(b): return int.from_bytes(b, "big")

def rnc_streams(data):
    out=[]; pos=0
    while True:
        i=data.find(b"RNC", pos)
        if i < 0: break
        if i+18 <= len(data) and data[i+3] in (1,2):
            u=be32(data[i+4:i+8]); p=be32(data[i+8:i+12])
            if u > 0 and p > 0 and i+18+p <= len(data):
                raw=data[i:i+18+p]
                out.append({
                    "off":i, "method":data[i+3], "unpacked":u, "packed":p,
                    "ucrc":be16(data[i+12:i+14]), "pcrc":be16(data[i+14:i+16]),
                    "sha256":hashlib.sha256(raw).hexdigest(),
                })
        pos=i+1
    return out

def diff_runs(a,b):
    n=min(len(a),len(b)); runs=[]; diff=0; i=0
    while i<n:
        if a[i]==b[i]: i+=1; continue
        s=i
        while i<n and a[i]!=b[i]: i+=1
        runs.append((s,i)); diff += i-s
    if len(a)!=len(b):
        runs.append((n,max(len(a),len(b)))); diff += abs(len(a)-len(b))
    return runs,diff

def identical_prefix(a,b):
    n=min(len(a),len(b)); i=0
    while i<n and a[i]==b[i]: i+=1
    return i

def identical_suffix(a,b):
    n=min(len(a),len(b)); i=0
    while i<n and a[len(a)-1-i]==b[len(b)-1-i]: i+=1
    return i

def main():
    blobs={name:path.read_bytes() for name,path in ROMS.items()}
    rncs={name:rnc_streams(data) for name,data in blobs.items()}
    lines=[
        "# Reference ROM Pairwise Comparison","",
        "Generated by `tools/compare_reference_roms.py`. Observations are byte-level facts; labels such as beta/prototype come from preservation/catalog identity, not inference from the differences.","",
        "## Pairwise summary","",
        "| Pair | Differing bytes | Diff runs | Identical prefix | Identical suffix | RNC byte-identical by content | Same-offset identical |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    pairs=[]
    for a,b in itertools.combinations(ROMS,2):
        da,db=blobs[a],blobs[b]
        runs,diff=diff_runs(da,db)
        ra={x["off"]:x for x in rncs[a]}; rb={x["off"]:x for x in rncs[b]}
        common_offsets=sorted(set(ra)&set(rb))
        same_offset=sum(1 for off in common_offsets if ra[off]["sha256"]==rb[off]["sha256"])
        hashes_a={x["sha256"] for x in rncs[a]}
        hashes_b={x["sha256"] for x in rncs[b]}
        same_content=len(hashes_a & hashes_b)
        pairs.append((a,b,runs,diff,same_content,same_offset,len(common_offsets)))
        lines.append(f"| {a} vs {b} | {diff:,} | {len(runs):,} | {identical_prefix(da,db):,} | {identical_suffix(da,db):,} | {same_content}/{len(rncs[a])} | {same_offset}/{len(common_offsets)} |")

    lines += ["", "## Largest differing runs by pair", ""]
    for a,b,runs,diff,same_content,same_offset,total_offsets in pairs:
        lines += [f"### {a} vs {b}","",f"- differing bytes: {diff:,}",f"- contiguous differing runs: {len(runs):,}",f"- RNC streams byte-identical by content: {same_content}/{len(rncs[a])}",f"- RNC streams identical at matching offsets: {same_offset}/{total_offsets}","- 20 largest differing runs:"]
        for ln,s,e in sorted(((e-s,s,e) for s,e in runs), reverse=True)[:20]:
            lines.append(f"  - `0x{s:06X}-0x{e-1:06X}`: {ln:,} bytes")
        lines.append("")

    lines += ["## RNC corpus cross-build identity", ""]
    offsets=sorted(set.intersection(*(set(x["off"] for x in rncs[name]) for name in ROMS)))
    same_at_common=0
    for off in offsets:
        entries=[next(x for x in rncs[name] if x["off"]==off) for name in ROMS]
        if len({e["sha256"] for e in entries})==1: same_at_common+=1
    hash_sets={name:{x["sha256"] for x in rncs[name]} for name in ROMS}
    all_hashes=set.intersection(*hash_sets.values())
    lines += [
        f"- Valid RNC offsets shared by all four builds: {len(offsets)}.",
        f"- Same-offset streams byte-identical across all four: {same_at_common}/{len(offsets)}.",
        f"- Streams byte-identical by content across all four regardless of offset: {len(all_hashes)}/45.",
        "",
        "Content matching is authoritative for cross-build RNC identity; offset matching is reported separately because packed assets may move between builds.",
        "",
    ]

    lines += ["## RNC location map", "", "| Build | First stream | Last stream | Count |", "|---|---:|---:|---:|"]
    for name in ROMS:
        xs=rncs[name]
        lines.append(f"| {name} | `0x{xs[0]['off']:06X}` | `0x{xs[-1]['off']:06X}` | {len(xs)} |")
    lines.append("")

    lines += ["## PAL-retail RNC changes by stream order", "",
              "The 45 streams are also compared by ordinal position. This is an observation aid, not yet proof that a stream ordinal equals a course identifier.",
              "",
              "| # | USA/prototype offset | PAL retail offset | USA packed/unpacked | PAL packed/unpacked | USA CRCs (P/U) | PAL CRCs (P/U) | Identical |",
              "|---:|---:|---:|---:|---:|---|---|:---:|"]
    usa=rncs["USA retail"]; pal=rncs["Europe retail"]
    for idx,(u,p) in enumerate(zip(usa,pal),1):
        if u["sha256"] != p["sha256"]:
            identical="no"
        else:
            identical="yes"
        lines.append(
            f"| {idx} | `0x{u['off']:06X}` | `0x{p['off']:06X}` | {u['packed']:,}/{u['unpacked']:,} | "
            f"{p['packed']:,}/{p['unpacked']:,} | `{u['pcrc']:04X}/{u['ucrc']:04X}` | "
            f"`{p['pcrc']:04X}/{p['ucrc']:04X}` | {identical} |"
        )
    lines.append("")
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text("\n".join(lines),encoding="utf-8")
    print(OUT)

if __name__=="__main__": main()
