#!/usr/bin/env python3
"""Structural probes over decoded RNC payloads, without assigning semantics."""
from pathlib import Path
from collections import Counter
from difflib import SequenceMatcher
from rnc_method1 import parse_header, unpack_method1

USA=Path("reference/roms/retail/Uniracers_USA.sfc")
PAL=Path("reference/roms/retail/Unirally_Europe.sfc")
OUT=Path("analysis/generated/rnc-payload-structure.md")

def streams(data):
    out=[]; pos=0
    while True:
        off=data.find(b"RNC\x01",pos)
        if off<0: return out
        h=parse_header(data[off:off+18])
        end=off+18+h.packed_size
        if h.unpacked_size and h.packed_size and end<=len(data):
            out.append((off,unpack_method1(data[off:end])))
        pos=off+1

def prefix_len(a,b):
    i=0
    while i<min(len(a),len(b)) and a[i]==b[i]: i+=1
    return i

def suffix_len(a,b):
    i=0
    while i<min(len(a),len(b)) and a[-1-i]==b[-1-i]: i+=1
    return i

def longest_run(data, value=0):
    best=cur=0
    for b in data:
        if b==value:
            cur+=1; best=max(best,cur)
        else: cur=0
    return best

def eq_shift(data, shift):
    if len(data)<=shift:return 0
    return sum(x==y for x,y in zip(data[:-shift],data[shift:]))/(len(data)-shift)

def hexb(data,n=48):
    return " ".join(f"{b:02x}" for b in data[:n])

def main():
    us=streams(USA.read_bytes()); ps=streams(PAL.read_bytes())
    lines=[
        "# Decoded RNC Payload Structural Probes","",
        "Generated by `tools/inspect_rnc_payloads.py`. These are mechanical byte-structure observations, not semantic claims about courses.","",
        "## USA payload signatures","",
        "| # | Size | First 48 decoded bytes | Longest 00 run | Most common bytes | Best repeat stride (1..256) |",
        "|---:|---:|---|---:|---|---|",
    ]
    shifts=[1,2,4,8,16,32,64,128,256]
    for i,(off,d) in enumerate(us,1):
        common=", ".join(f"{v:02X}:{n}" for v,n in Counter(d).most_common(4))
        scores=[(eq_shift(d,s),s) for s in shifts]
        score,s=max(scores)
        lines.append(f"| {i} | {len(d):,} | `{hexb(d)}` | {longest_run(d)} | {common} | {s} ({score:.3f}) |")

    lines += ["","## Seven decoded USA/PAL deltas","",
              "SequenceMatcher is used only to summarize locality. Its edit decomposition is not treated as a file-format interpretation.","",
              "| # | Size delta | Common prefix | Common suffix | Matching bytes in blocks | Edit blocks (equal/replace/insert/delete) | First non-equal opcode |",
              "|---:|---:|---:|---:|---:|---|---|"]
    for i,((uo,u),(po,p)) in enumerate(zip(us,ps),1):
        if u==p: continue
        sm=SequenceMatcher(None,u,p,autojunk=False)
        ops=sm.get_opcodes()
        counts=Counter(tag for tag,*_ in ops)
        matching=sum(i2-i1 for tag,i1,i2,j1,j2 in ops if tag=="equal")
        first=next(op for op in ops if op[0]!="equal")
        tag,i1,i2,j1,j2=first
        lines.append(
            f"| {i} | {len(p)-len(u):+,} | {prefix_len(u,p):,} | {suffix_len(u,p):,} | {matching:,} | "
            f"{counts.get('equal',0)}/{counts.get('replace',0)}/{counts.get('insert',0)}/{counts.get('delete',0)} | "
            f"`{tag} U[{i1}:{i2}] P[{j1}:{j2}]` |"
        )
        lines += [
            f"",
            f"### Stream {i}",
            f"",
            f"- USA first 64: `{hexb(u,64)}`",
            f"- PAL first 64: `{hexb(p,64)}`",
            f"- USA last 64: `{hexb(u[-64:],64)}`",
            f"- PAL last 64: `{hexb(p[-64:],64)}`",
            f"- edit opcodes (first 20):",
        ]
        for op in ops[:20]:
            tag,i1,i2,j1,j2=op
            lines.append(f"  - {tag}: USA {i1}:{i2} ({i2-i1}) ; PAL {j1}:{j2} ({j2-j1})")
    OUT.parent.mkdir(parents=True,exist_ok=True)
    OUT.write_text("\n".join(lines)+"\n",encoding="utf-8")
    print(OUT)

if __name__=="__main__": main()
