#!/usr/bin/env python3
"""Inventory every preserved reference ROM without embedding ROM bytes in reports."""
from pathlib import Path
import hashlib
import zlib

ROOT = Path("reference/roms")
OUT = Path("analysis/generated/reference-rom-inventory.md")

def snes_header(data: bytes):
    h = data[0x7FC0:0x8000]
    if len(h) < 0x40:
        return {}
    return {
        "title": h[:21].rstrip(b"\x00 ").decode("ascii", "replace"),
        "map": h[0x15],
        "cart": h[0x16],
        "rom": h[0x17],
        "sram": h[0x18],
        "region": h[0x19],
        "developer": h[0x1A],
        "version": h[0x1B],
        "complement": int.from_bytes(h[0x1C:0x1E], "little"),
        "checksum": int.from_bytes(h[0x1E:0x20], "little"),
        "reset": int.from_bytes(data[0x7FFC:0x7FFE], "little") if len(data) >= 0x7FFE else None,
    }

def rnc_count(data: bytes):
    hits = 0
    method1 = 0
    pos = 0
    while True:
        i = data.find(b"RNC", pos)
        if i < 0:
            break
        hits += 1
        if i + 18 <= len(data) and data[i+3] == 1:
            packed = int.from_bytes(data[i+8:i+12], "big")
            unpacked = int.from_bytes(data[i+4:i+8], "big")
            if packed > 0 and unpacked > 0 and i + 18 + packed <= len(data):
                method1 += 1
        pos = i + 1
    return hits, method1

def main():
    paths = sorted(p for p in ROOT.rglob("*") if p.is_file() and p.suffix.lower() in {".sfc", ".smc"})
    rows = []
    for path in paths:
        data = path.read_bytes()
        h = snes_header(data)
        hits, method1 = rnc_count(data)
        rows.append({
            "path": str(path),
            "size": len(data),
            "crc32": f"{zlib.crc32(data) & 0xffffffff:08x}",
            "md5": hashlib.md5(data).hexdigest(),
            "sha1": hashlib.sha1(data).hexdigest(),
            "sha256": hashlib.sha256(data).hexdigest(),
            "title": h.get("title", ""),
            "region": h.get("region"),
            "version": h.get("version"),
            "reset": h.get("reset"),
            "checksum": h.get("checksum"),
            "complement": h.get("complement"),
            "rnc_hits": hits,
            "rnc_m1": method1,
        })

    lines = [
        "# Reference ROM Inventory",
        "",
        "Generated by `tools/inventory_reference_roms.py`. This report records identities and structural observations only; it contains no ROM payload.",
        "",
        "| Path | Size | CRC32 | SHA-1 | SHA-256 | Header title | Region | Ver | Reset | RNC M1 |",
        "|---|---:|---|---|---|---|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['path']}` | {r['size']:,} | `{r['crc32']}` | `{r['sha1']}` | `{r['sha256']}` | "
            f"{r['title']} | 0x{r['region']:02X} | {r['version']} | `0x{r['reset']:04X}` | {r['rnc_m1']} |"
        )

    lines += ["", "## Full digests and checksum fields", ""]
    for r in rows:
        lines += [
            f"### `{r['path']}`",
            "",
            f"- MD5: `{r['md5']}`",
            f"- SHA-1: `{r['sha1']}`",
            f"- SHA-256: `{r['sha256']}`",
            f"- CRC32: `{r['crc32']}`",
            f"- SNES header checksum/complement: `0x{r['checksum']:04X}` / `0x{r['complement']:04X}`",
            f"- ASCII RNC occurrences: {r['rnc_hits']}; plausible Method 1 streams: {r['rnc_m1']}",
            "",
        ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUT)

if __name__ == "__main__":
    main()
